language: python
python: "2.7"
cache:
  directories:
    - $HOME/.cache/pip
install:
  # TODO: use requirements.txt when ansible updated to >= 1.9
  - pip install ansible
  - pip install -r test-requirements.txt
script:
  - ansible-playbook --syntax-check -i hosts site.yml
  - ansible-lint site.yml
